# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Finn Jules Kramer"
subtitle: "See the world through my eyes!"
author: "Finn Jules Kramer"
header:
 title: "Architecture & Horticulture"
 subtitle: "by Finn Jules Kramer"
footer:
 name: "Finn Jules Kramer"
 bio: "lorem ipsum whatever you want to say"


site_author: "Menno Kramer"
parent_theme: "https://github.com/rampatra/photography"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[]'
social_urls:
  twitter: ""
  instagram: "https://www.instagram.com/framerarch"
  linkedin: ""
  github: ""
